server:
  port: 8083
spring:
  application:
    name: manage-staff-service
  datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/staffdb
     username: root
     password: 1234
  jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true
