server:
    port: 8086
spring:
    application:
         name: make-reservation-service
    data:
     mongodb:
      host: localhost
      port: 27017
      database: reservationdb
    main:
      allow-circular-references: true

