server:
  port: 8088
spring:
  application:
    name: manage-guest-service
  datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/guestdb
     username: root
     password: 1234
  jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true
logging:
  level:
    com:
      capgemini:
        manageguestservice: INFO
